[project]
name = "pytntnn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["numpy", "scipy"]

[dependency-groups]
dev = ["scikit-learn"]
